version: '3.5'


services:
  postgres:
    container_name: postgres_anime
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"


  redis:
    container_name: cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis:/data


volumes:
  postgres-db:
    driver: local
  redis:
    driver: local