version: '3.5'

services:
#  backend:
#    build: .
#    depends_on:
#      - db

  postgres:
    container_name: db
    image: postgres:15-alpine
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres

  redis:
    container_name: cache
    image: redis:7-alpine
    volumes:
      - redis:/data/redis
    ports:
      - "6379:6379"

volumes:
  postgres-db:
  redis:
